NSO-developer/drned-xmnr

drned/drned/device.py
The corresponding change to DrNED already merged (PR 32).
=> Ignoring messages from parallel commits in ncs_cli interactions.

python/drned_xmnr/op/base_op.py
=> Allow non-default NCS IPT port.

python/drned_xmnr/op/config_op.py, test/unit/test_actions.py
Redundant namespace declaration removed and a failing test case fixed.
=> fix redundant xslt namespace declaration

python/drned_xmnr/op/filtering.py, test/lux/basic.lux, test/lux/common.luxinc
The code needed some changes to work with recent DrNED; still works with the "built-in DrNED". Also minor changes (only in the lux test, actually) were needed to work with NSO 5.1+ due to the mandatory ned-id.
=> adapting to recent DrNED and to NSO 5.2

Pipfile, README.md
Extended README to mention Python 3 as the preferred variant.
=> fixed package names, few words on Python 2/3

python/drned_xmnr/op/config_op.py
=> Replace deprecated function name

drned-skeleton/cli2netconf.py, python/drned_xmnr/action.py, python/drned_xmnr/op/base_op.py, python/drned_xmnr/op/config_op.py, src/yang/drned-xmnr.yang, test/lux/basic.lux, test/lux/cfgs/device/cisco-nc0.py, test/lux/cfgs/rad1.cfg, test/lux/cfgs/rad2.cfg, test/lux/cfgs/short-rad1.cfg, test/lux/cfgs/short-rad2.cfg, test/lux/clined.lux, test/lux/common.luxinc
Implementation of the action `import-convert-cli-files` - convert CLI-NED configuration files to NETCONF-NED configuration files and import them as xmnr states.
=> Import / convert CLI-NED config files

drned-skeleton/cli2netconf.py, python/drned_xmnr/op/config_op.py, src/yang/drned-xmnr.yang, test/lux/cfgs/device/cisco-nc0.py, test/lux/clined.lux
* reverts "load" clined state to "put" to keep compatibility with DrNED's device drivers
* adds timeout leaf for the action
=> fixes in the import-convert action

.gitignore, drned/drned/device.py
=> Add missing regexp end-of-line anchor. Also, ignore test logs.

drned/common/test_coverage.py, drned/common/test_template.py
=> Fix invalid escape sequence warnings

drned/common/test_common.py, drned/common/test_coverage.py, drned/common/test_here.py, drned/common/test_incomplete.py, drned/common/test_template.py, drned/drned/__init__.py, drned/drned/choice.py, drned/drned/device.py, drned/drned/fixtures.py, drned/drned/node.py, drned/drned/schema.py, drned/drned/stage.py
=> A bunch of pep8 fixes.

python/drned_xmnr/op/filtering.py, test/unit/test_actions.py
Drned output log filtering state machine and log states implementation changed; (expected) advantages of the new implementation:
* clearer state transition mechanism
* better documented.
=> filtering log states reworked

.gitignore, drned/common/test_template.py, drned/drned/device.py, drned/drned/fixtures.py, python/drned_xmnr/op/base_op.py, python/drned_xmnr/op/config_op.py, python/drned_xmnr/op/filtering.py, python/drned_xmnr/op/transitions_op.py, src/yang/drned-xmnr.yang
=> Add errror recovery to walk-states so it continues if a state failes.

drned-skeleton/cli2netconf.py, drned/common/test_template.py, drned/drned/fixtures.py, python/drned_xmnr/op/filtering.py
=> Resurrect print summary of failed states which broke after the new state machine was introduced.

python/drned_xmnr/op/config_op.py
=> Apply configured device-timeout.

drned-skeleton/cli2netconf.py, drned-skeleton/devcli.py, drned-skeleton/load-default-config.py, drned/drned/device.py, python/drned_xmnr/action.py, python/drned_xmnr/op/base_op.py, python/drned_xmnr/op/common_op.py, python/drned_xmnr/op/config_op.py, src/yang/drned-xmnr.yang, test/unit/test_actions.py, test/unit/test_cli2netconf.py
=> Load default config

python/drned_xmnr/op/common_op.py
=> Remove leftover timeout argument in call to run_in_drned_env()

drned-skeleton/cli2netconf.py, drned-skeleton/save-default-config.py, python/drned_xmnr/action.py, python/drned_xmnr/op/common_op.py, src/yang/drned-xmnr.yang, test/unit/test_cli2netconf.py
Signed-off-by: Jozef Miklos <jomiklos@cisco.com>
=> add new save-default-config action to overwrite default state

test/lux/basic.lux
Signed-off-by: Michal Novak <micnovak@cisco.com>
=> drned-xmnr Issue #82 - skip rollback on empty commit - test

python/drned_xmnr/op/config_op.py, test/lux/clined.lux
Filter out all non-files from the parameter list, bail out if nothing remains.
=> filter out directories for importing

drned/adm/test_builtin.py, drned/common/test_common.py, drned/common/test_coverage.py, drned/drned/__init__.py, drned/drned/fixtures.py, drned/drned/schema.py, python/drned_xmnr/check_action.py, python/drned_xmnr/op/base_op.py, python/drned_xmnr/op/coverage_op.py, requirements.txt, test/lux/common.luxinc, test/lux/requirements.txt, test/unit/requirements.txt
Removing the path pointing to the NSO distribution of pyang and adding pyang to pypi requirements; plus few minor related changes.
=> require the open-source pyang so as to make coverage work

python/drned_xmnr/op/transitions_op.py, test/unit/test_filters.py
Signed-off-by: Martin Volf <mvolf@cisco.com>
=> making flake8 happy

python/drned_xmnr/op/config_op.py, test/unit/test_actions.py
Fixed the format test for the record action.
=> fixed recorded state format handling
