NSO-developer/drned-xmnr

- python/drned_xmnr/op/base_op.py
- test/unit/test_actions.py
Log files storing DrNED and filtered DrNED output were global; this is causing issues when multiple tests are run in parallel towards multiple devices. This change makes the two files local per device. Related to #5.
> separate drned logs and redirect logs for devices

- python/drned_xmnr/op/filtering.py
- test/unit/test_actions.py
Recent versions of Python3 issue deprecation warnings for incorrect escape sequences and for the use (or unhandled occurrence) of StopIteration in a generator. The change is fixing them.
> deprecation warnings fixes (escape sequences in regexes, PEP 479)

- drned/adm/setup.cfg
The new format has been understood by pytest for three years and is
required by ptest 4.2.0 and later versions.
> Update section header [pytest] -> [tool:pytest].

- Pipfile
- README.md
- requirements.txt
Added `requirements.txt` (to be used by `pip`) and `Pipfile` (to be used by `pipenv`). Expanded README to describe in more detail what is required by the tool and how to install it.
> requirements stated more explicitly

- drned/drned/fixtures.py
- test/lux/basic.lux
- test/lux/clined.lux
- test/lux/common.luxinc
- test/unit/tox.ini
The problem is in that DrNED used "load replace" to restore the original device configuration and this usually fails; its current code works around the problem by simply erasing the device config and "load merge" the saved configuration. This commit uses the new device fixture code.
> incorporating changes in the device fixture in the original DrNED

- python/drned_xmnr/op/config_op.py
- test/lux/basic.lux
- test/lux/subnet.xml
Rewritten `import-states` with `merge="false"` so that the actual load operation is merge, but the device config is deleted before that.
> import-states without merge

- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/coverage_op.py
- python/drned_xmnr/op/transitions_op.py
Run `which $executable` for several meaningful pytest executable names.
> look up the correct pytest executable before starting the test

- drned/drned/device.py
DrNED behaves incorrectly when there are no rollback files (either because there really are not none, or because they are configured to be located in an unusual location).
> fix behavior when there are no rollback files found

- Pipfile
- drned/drned/fixtures.py
- python/drned_xmnr/op/transitions_op.py
- requirements.txt
- test/unit/test_actions.py
In pytest>=6.0 some characters are no longer allowed in test parameters. For some DrNED tests we were using file paths as test parameters, moreover conversion `'-' -> '~'` was done (perhaps for some legacy reasons); neither `'/'` or `'~'` are allowed. Change consists of two small parts:
- In DrNED, assign IDs to file parameters; the ID is created as the base name of the file. The conversion `'-' -> '~'` is not necessary, so it was removed.
- In XMNR, use just IDs, i.e. the file name without the path part.
It is yet another step away from the original DrNED, albeit small.
The change seems to be backward compatible (at least seems to work with pytest-5.4.3).
> working with pytest>=6.0

- python/drned_xmnr/op/filtering.py
- python/drned_xmnr/op/setup_op.py
- src/yang/drned-xmnr.yang
- test/lux/basic.lux
- test/lux/common.luxinc
- test/unit/test_actions.py
The first commit adds a switch to disable commit queues for a device during xmnr-setup; the second fixes walk-transitions and explore-transitions output and adds a test to verify the switch behavior.
> No commit queues

- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/config_op.py
- python/drned_xmnr/op/filtering.py
- test/lux/basic.lux
- test/lux/common.luxinc
- test/lux/subnet2.xml
State file discovery now takes into account also files that do not contain `".state."` in their name - enough if it ends with `.xml` or `.cfg`. Copying file like `ABC.xml` to a state directory that already contains `ABC.state.xml` leads to somewhat unpredictable behavior.
> ".state." part of the state file is now optional

- python/drned_xmnr/op/transitions_op.py
- test/lux/basic.lux
- test/lux/common.luxinc
If the user does not provide its own set of states, the action walk-states
makes sure that one file set is represented by only one state.
As a result, the walk-states action output would look like
```
admin@ncs(config-device-dhcp0)# drned-xmnr transitions walk-states 
Prepare the device
Test transition to sbnet:*
Test transition to empty
Device cleanup
success Completed successfully
admin@ncs(config-device-dhcp0)# 
```
> walk-states now works with file sets, fixes #30

- drned-skeleton/cli2netconf.py
- python/drned_xmnr/op/setup_op.py
Few changes needed to make XMNR run on Python 2.7 again.
> fixing Python 2.7 support

- README.md
- package-meta-data.xml
- python/drned_xmnr/check_action.py
- python/drned_xmnr/op/coverage_op.py
- test/unit/mocklib.py
- test/unit/requirements.txt
- test/unit/test_check.py
- test/unit/tox.ini
This change also fixes some cross-release issues and especially makes the unit tests pass on the supported Python versions.
> fixes #33: new dummy component performs initial sanity checks

- drned/drned/device.py
- python/drned_xmnr/op/config_op.py
- python/drned_xmnr/op/transitions_op.py
- src/yang/drned-xmnr.yang
- test/lux/basic.lux
Add optional timeouts to potentially long-running import and walk-states commands.
(Also, add missing view-state test-case and remove some dead code)
> Add optional timeouts to potentially long-running import and walk-states commands.

- drned/common/test_template.py
- python/drned_xmnr/action.py
- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/setup_op.py
- src/yang/drned-xmnr.yang
- test/lux/basic.lux
Implementation of the `abort` callback; it first sets a `aborted` flag, then sends ctrl-c to the running pytest process, then kills it if it does not terminate within given period.
> support for ctrl-c abort

- python/drned_xmnr/op/config_op.py
- python/drned_xmnr/op/filtering/events.py
* minor changes in import failures - improved incomprehensible messages in case of bad file format
* larger changes in convert: yet another message filtering mechanism (but much simpler than for transitions) to yield better output
May need some work to coordinate with the load-default branch.
> import and convert failure message improvement

- drned-skeleton/cli2netconf.py
Move `interstate_one("enter")` to the connection part to make sure ssh connects successfully.
> Devcli: moved device login into the connection part

- drned-skeleton/cli2netconf.py
- python/drned_xmnr/op/config_op.py
- test/lux/clined.lux
- test/unit/test_cli2netconf.py
When a conversion of one state is completed, the state is immediately added to the device states, so that if the action crashes or is aborted, the states converted before the crash stay available.
> states properly imported continuously

- python/drned_xmnr/op/config_op.py
- python/drned_xmnr/op/filtering/events.py
- test/unit/test_actions.py
Import and import-convert now remove only the last `.part`, except for the case when this is preceded by `".state"` - this is removed as well then. Dots in state names are supported now.
> support for state names containing dot characters

- drned-skeleton/cli2netconf.py
- drned-skeleton/devcli.py
- drned-skeleton/load-default-config.py
- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/common_op.py
- python/drned_xmnr/op/config_op.py
- src/yang/drned-xmnr.yang
- test/lux/cfgs/device/netsim_I.py
- test/lux/clined.lux
- test/lux/etrafo/usr/device/netsim_J.py
- test/lux/timeouts.lux
- test/unit/mocklib.py
- test/unit/test_cli2netconf.py
XMNR sends a set of device parameters down to devcli which makes them available to device drivers, so that it is not necessary to modify the driver/its .cfg file each time it is used with a new device of the same type.
> smarter passing of parameters to devcli

- python/drned_xmnr/op/config_op.py
- src/yang/drned-xmnr.yang
- test/lux/clined.lux
- test/unit/test_actions.py
add new parameter for import-state-files to allow continuation of previously interrupted run
Signed-off-by: Jozef Miklos <jomiklos@cisco.com>
> new skip-existing parameter for import-state-files

- python/drned_xmnr/action.py
- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/config_op.py
- python/drned_xmnr/op/transitions_op.py
- src/yang/drned-xmnr.yang
- test/lux/basic.lux
- test/lux/clined.lux
- test/lux/timeouts.lux
- test/unit/test_actions.py
The change implements two new features:
* input parameter `ignore-states` for the actions "walk" and "explore"; it tells XMNR to walk/explore all (enabled) states except those to be ignored;
* two actions `disable-state` and `enable-state`; a disabled state is automatically ignored in the "walk" and "explore" actions, unless explicitly told otherwise.
> support for ignored and disabled states

- drned-skeleton/cli2netconf.py
- drned-skeleton/devcli.py
- drned-skeleton/load-default-config.py
- python/drned_xmnr/op/common_op.py
- python/drned_xmnr/op/config_op.py
- test/lux/cfgs/device/netsim_I.py
- test/lux/clined.lux
Devcli now supports a new driver state "authfailed" - if the driver enters the state, Devcli immediately raises an exception which is subsequently spotted by XMNR itself and a corresponding message is displayed to the user. Devcli filtering was slightly refactored and applied also to the load-default action.
> better messages for SSH authentication failures

- drned-skeleton/cli2netconf.py
- drned-skeleton/devcli.py
- drned-skeleton/load-default-config.py
- python/drned_xmnr/op/common_op.py
- test/lux/basic.lux
- test/lux/timeouts.lux
With this change, devcli differs between disconnect/timeout while connecting or logging into the device and timeout while doing the real stuff. So now, if the device times out because particular state causes issues, cli2netconf is able to continue; if it times out in the initial phases of the connection, cli2netconf gives up and XMNR reports a timeout/connection issue.
> watching for device timeout/disconnect in devcli

- drned/drned/device.py
In 5.5 or later the state file may be empty, in particular it would not contain even the device name.  DrNED makes sure that the device name in a state file is correct, but it always assumes it is there.
> device renaming in DrNED done carefully for .xml files

- drned-skeleton/cli2netconf.py
- drned-skeleton/devcli.py
- drned-skeleton/load-default-config.py
- drned-skeleton/save-default-config.py
- drned/drned/device.py
- python/drned_xmnr/op/common_op.py
- python/drned_xmnr/op/config_op.py
- test/lux/etrafo/usr/device/netsim_J.py
- test/lux/timeouts.lux
- test/unit/test_cli2netconf.py
The `timeouts` test was failing intermittently; one reason was a race condition in the test itself, but other reasons were also that timeout behavior was quite unpredictable, and there were actual bugs in how they were handled.
Most important changes are:
* the device driver used in the test and the test itself synchronize to prepare timeout scenarios;
* removed DrNED's `Device` from `Devcli`; the few actions for which `Device` was used are replaced by MAAPI calls;
* timeout/failure during `restore_config` is handled separately - in that case the action is aborted; added test for this scenario.
> better device timeout handling & testing

- drned-skeleton/cli2netconf.py
- drned-skeleton/devcli.py
`sync-from` raised a non-recoverable exception - this has been changed.
> sync-from failure raises noncritical exception

- python/drned_xmnr/op/base_op.py
- python/log_action.py
- src/yang/drned-xmnr.yang
Adds two new options:
* when `/drned-xmnr/cli-log-file` is configured (with absolute path, preferably), XMNR sends to that file every line that would be sent to CLI;
* when a daemon registers `xmnr-cli-log` actionpoint, that daemon will receive action callbacks with every line that would be sent to CLI.
An example logging daemon is part of the commit:
```
xmnr$ cd python/
xmnr/python$ export PYTHONPATH=${NCS_DIR}/src/ncs/pyapi
xmnr/python$ ./log_action.py --help
usage: log_action.py [-h] [-i IP] [-p PORT]
optional arguments:
-h, --help            show this help message and exit
-i IP, --ip IP
-p PORT, --port PORT
xmnr/python$ ./log_action.py
logger started, hit <ENTER> to quit
dhcp0: importing state c-cfg
dhcp0: importing state s-dlt
xmnr/python$ 
```
> CLI output to file and/or action

- .github/workflows/drned-xmnr-unit.yml
- README.md
- python/drned_xmnr/action.py
- python/drned_xmnr/common_types.py
- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/common_op.py
- python/drned_xmnr/op/parse_log_errors.py
- python/drned_xmnr/op/transitions_op.py
- src/yang/drned-xmnr.yang
without show template for now, and possibly broken device specific log finding...
assuming we have some device DDD running, following commands can be executed in CLI to try to parse and show problems form the common XMNR log.
Any `parse-log-errors` action invocation overwrites/deletes any previously parsed problems form the target `parsed-problems` table...
```
config
devices device DDD
drned-xmnr parse-log-errors target-log common-xmnr-log
do show devices device DDD drned-xmnr parsed-problems 
```
> draft parse-log-errors action

- README.md
- drned-skeleton/devcli.py
- python/drned_xmnr/action.py
- python/drned_xmnr/check_action.py
- python/drned_xmnr/op/base_op.py
- python/drned_xmnr/op/setup_op.py
- test/unit/mocklib.py
- test/unit/test_actions.py
- test/unit/test_check.py
- test/unit/test_cli2netconf.py
- test/unit/test_filters.py
- test/unit/tox.ini
With recent changes and with type annotations on the way, we no longer support Python 2 - removing all `sys.version_info` checks and related stuff.
> Python 2 no longer supported

- src/yang/drned-xmnr.yang
- test/lux/basic.lux
The record formats are now both `nso-*` so that the name is consistent with the import format; and the import default format is `nso-xml`.
Note that this change may break some scripts.
> changed record and import format options and defaults

- README.md
- python/drned_xmnr/op/coverage_op.py
- python/drned_xmnr/op/setup_op.py
- test/unit/mocklib.py
- test/unit/test_actions.py
`coverage collect`, if not provided with a list of YANG patterns, now tries to look up the NED package and use its modules. Also, the feature description has been extended.
> coverage collect is able to work with NED modules by default

- python/drned_xmnr/op/setup_op.py
The `print` function does not work on NSO 6.0; presumably it has been redefined in its VM.
> do not use "print" when writing to file

- python/drned_xmnr/action.py
- test/unit/test_actions.py
Making XMNR a bit more thread-safe.  It is far from being bullet-proof though - if two parallel sessions modify the list of states for the same device, the results may be surprising; but if the two sessions have different devices, it should be fine.
> action handlers are accessed thread-safely
